{{- if .Values.ingress.enabled -}}
 
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: {{ template "pact-broker.fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    app: "{{ .Chart.Name | replace "-" "_" }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: pact-broker
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
